def solution(string1, string2):
    cache = [[0 for i in range(1000)] for j in range(1000)]
    i, j = 0, 0
    while i < len(string1) and j < len(string2):
        return 0


# 4 31 1 200 10 10 13
# 4
print(solution("ACAYKP", "CAPCAK"))
# 31
print(solution("AACGGAACACGCTTTAAGGGCGATGGAATACCGTGGGTTTACCTAAAACTA", "AATCTGGCCTATTCTGGGTCAAATGGCGTGAGCAAACATCGTACA"))
# 1
print(solution("CAPCK", "AA"))
# 200
print(solution("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"))
# 10
print(solution("SKDFHWEODJKSFSDFJK", "WKJSDHFOWEFKJDVKSDF"))
# 10
print(solution("KJSDFKSDFLKDFJS", "SKDJKFLSKDJFLKSDJF"))
# 13
print(solution("LKSDJFLKJWPOJSDLKJFSDF", "OISJDKFJLKEJFSLKJDIFJSLDK"))
